// Code generated by "stringer -type Kind -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[Invalid-1]
	_ = x[OpenParen-2]
	_ = x[CloseParen-3]
	_ = x[OpenBrace-4]
	_ = x[CloseBrace-5]
	_ = x[Comma-6]
	_ = x[Dot-7]
	_ = x[Minus-8]
	_ = x[Plus-9]
	_ = x[SemiColon-10]
	_ = x[Slash-11]
	_ = x[Star-12]
	_ = x[Bang-13]
	_ = x[BangEq-14]
	_ = x[Eq-15]
	_ = x[DoubleEq-16]
	_ = x[Greater-17]
	_ = x[GreaterEq-18]
	_ = x[Less-19]
	_ = x[LessEq-20]
	_ = x[Ident-21]
	_ = x[String-22]
	_ = x[Number-23]
	_ = x[And-24]
	_ = x[Class-25]
	_ = x[Else-26]
	_ = x[False-27]
	_ = x[Fun-28]
	_ = x[For-29]
	_ = x[If-30]
	_ = x[Nil-31]
	_ = x[Or-32]
	_ = x[Print-33]
	_ = x[Return-34]
	_ = x[Super-35]
	_ = x[This-36]
	_ = x[True-37]
	_ = x[Var-38]
	_ = x[While-39]
}

const _Kind_name = "EOFInvalidOpenParenCloseParenOpenBraceCloseBraceCommaDotMinusPlusSemiColonSlashStarBangBangEqEqDoubleEqGreaterGreaterEqLessLessEqIdentStringNumberAndClassElseFalseFunForIfNilOrPrintReturnSuperThisTrueVarWhile"

var _Kind_index = [...]uint8{0, 3, 10, 19, 29, 38, 48, 53, 56, 61, 65, 74, 79, 83, 87, 93, 95, 103, 110, 119, 123, 129, 134, 140, 146, 149, 154, 158, 163, 166, 169, 171, 174, 176, 181, 187, 192, 196, 200, 203, 208}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
